### ISSUE TITLE
Is it possible to run MBPTrack on CPU?

### ISSUE THREAD

**Issue by MaxTeselkin** [slothfulxtx/MBPTrack3D#3]
Hi, I need to run MBPTrack on CPU. As far as I understood, your code (main.py) supports only GPU inference. I guess MBPTrack is not very computationally expensive, is it possible to run it on CPU?

**Comment by slothfulxtx** [comment]
Hi, thanks for your interst. Yes, you can implement MBPTrack on CPU with some minor modification, because our code does not rely on GPU specific env or code. For example, you may remove some code related to pynvml, which is used for finding the GPU that is not occupied.

**Comment by slothfulxtx** [comment]
Sorry, I've just noted that pointnet-ops may not support CPU env, you can replace these code with pytorch3d. All these point cloud operators have been implemented in pytorch3d.
