### ISSUE TITLE
Checkpoints for Waymo dataset

### ISSUE THREAD

**Issue by MaxTeselkin** [slothfulxtx/MBPTrack3D#8]
Hi! There are checkpoints for KITTI and NuScenes in google drive link which you provided in README, but there aren't checkpoints for Waymo dataset. Are you planning to open-source them?

<img width="1180" alt="image" src="https://github.com/slothfulxtx/MBPTrack3D/assets/91027877/b0a40184-a8ce-4c40-93f3-f36d19ac8282">

**Comment by slothfulxtx** [comment]
hi, we only test the generalization ability of MBPTrack with pretrained models on KITTI, as described in our paper
![image](https://github.com/slothfulxtx/MBPTrack3D/assets/37545740/390d16bd-83f1-40ad-9993-0cdfe81f3b6b)
Thus, we donot train our model from scratch using Waymo data. You can just load the kitti ckpt to reproduce the performance on waymo.
